# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-07 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='birth',
            field=models.CharField(default='unknown', max_length=50, verbose_name='birth'),
        ),
    ]
