# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_myuser_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='actList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actName', models.CharField(max_length=50, verbose_name='actName')),
                ('actSummary', models.CharField(max_length=50, verbose_name='actName')),
                ('actInfo', models.CharField(max_length=50, verbose_name='actName')),
            ],
        ),
        migrations.AlterField(
            model_name='myuser',
            name='birth',
            field=models.DateField(help_text='반드시 양식을 지켜주세요', max_length=50, verbose_name='birth'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(help_text='한글가능', max_length=20, unique=True, verbose_name='nickname'),
        ),
        migrations.AddField(
            model_name='actlist',
            name='actId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
