# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20170520_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actlist',
            name='actInfo',
            field=models.TextField(blank=True, max_length=50, verbose_name='actInfo'),
        ),
        migrations.AlterField(
            model_name='actlist',
            name='actName',
            field=models.CharField(max_length=20, unique=True, verbose_name='actName'),
        ),
        migrations.AlterField(
            model_name='actlist',
            name='actSummary',
            field=models.CharField(max_length=50, null=True, verbose_name='actSumary'),
        ),
    ]
