# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20170523_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='actlist',
            name='actNum',
            field=models.CharField(default=-11111, max_length=15, unique=True, verbose_name='계좌번호'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actlist',
            name='actInfo',
            field=models.TextField(blank=True, max_length=50, verbose_name='통장정보'),
        ),
        migrations.AlterField(
            model_name='actlist',
            name='actName',
            field=models.CharField(max_length=20, verbose_name='통장이름'),
        ),
        migrations.AlterField(
            model_name='actlist',
            name='actSummary',
            field=models.CharField(max_length=50, null=True, verbose_name='한줄설명'),
        ),
    ]
