# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_actlist_actnum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actlist',
            old_name='actId',
            new_name='act',
        ),
        migrations.RemoveField(
            model_name='actlist',
            name='id',
        ),
        migrations.AlterField(
            model_name='actlist',
            name='actNum',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='계좌번호'),
        ),
    ]
