# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20170529_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_date', models.DateField(verbose_name='날짜')),
                ('act_price', models.IntegerField(verbose_name='금액')),
                ('act_payment', models.BooleanField(verbose_name='카드(T)/현금(F)')),
                ('act_part', models.BooleanField(verbose_name='수입(T)/지출(F)')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ActList')),
            ],
        ),
    ]
