# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_bankbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbook',
            name='act_part',
            field=models.CharField(max_length=6, verbose_name='수입/지출'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='act_payment',
            field=models.CharField(max_length=6, verbose_name='카드/현금'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ActList'),
        ),
    ]
