# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20170602_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbook',
            name='act_total',
            field=models.IntegerField(blank=True, default=0, max_length=15, verbose_name='잔여금액'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ActList'),
        ),
    ]
