# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-27 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20170619_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbook',
            name='act_content',
            field=models.CharField(default=' ', max_length=50, verbose_name='소비내용'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ActList'),
        ),
    ]
