# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 04:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20170627_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_title', models.CharField(max_length=40, verbose_name='글제목')),
                ('board_content', models.CharField(max_length=3000, verbose_name='글내용')),
                ('board_time', models.DateTimeField(max_length=20, verbose_name='작성시간')),
                ('board_hit', models.IntegerField(default=0, verbose_name='조회수')),
                ('board_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='act_total',
            field=models.IntegerField(default=0, verbose_name='잔여금액'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ActList'),
        ),
    ]
