# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-02 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20170701_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actboard',
            name='board_time',
        ),
        migrations.AddField(
            model_name='actboard',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='작성시간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='actboard',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='작성시간'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ActList'),
        ),
    ]
