# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-02 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20170702_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actboard',
            name='board_nick',
            field=models.CharField(max_length=40, verbose_name='닉네임'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ActList'),
        ),
    ]
