# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20170703_0054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actboard',
            name='board_hit',
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ActList'),
        ),
    ]
