# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 02:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20170704_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='actboard',
            name='board_hit',
            field=models.IntegerField(default=0, verbose_name='조회'),
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ActList'),
        ),
    ]
