# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_auto_20170710_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Post')),
            ],
        ),
        migrations.RenameField(
            model_name='actcomment',
            old_name='author',
            new_name='actauthor',
        ),
        migrations.RenameField(
            model_name='actcomment',
            old_name='created_at',
            new_name='actcreated_at',
        ),
        migrations.RenameField(
            model_name='actcomment',
            old_name='message',
            new_name='actmessage',
        ),
        migrations.RenameField(
            model_name='actcomment',
            old_name='post',
            new_name='actpost',
        ),
        migrations.RenameField(
            model_name='actcomment',
            old_name='updated_at',
            new_name='actupdated_at',
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ActList'),
        ),
    ]
