# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-10 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_auto_20170710_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actcomment',
            old_name='actauthor',
            new_name='act_author',
        ),
        migrations.RenameField(
            model_name='actcomment',
            old_name='actcreated_at',
            new_name='act_created_at',
        ),
        migrations.RenameField(
            model_name='actcomment',
            old_name='actmessage',
            new_name='act_message',
        ),
        migrations.RenameField(
            model_name='actcomment',
            old_name='actpost',
            new_name='act_post',
        ),
        migrations.RenameField(
            model_name='actcomment',
            old_name='actupdated_at',
            new_name='act_updated_at',
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ActList'),
        ),
    ]
