# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-11 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_auto_20170711_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankbook',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.ActList'),
        ),
    ]
